server:
  port: 8080
  servlet:
    context-path: /api
    
logging:
  level:
    root: INFO

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    enable:
        http.client.requests: true 
    distribution:
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: true

pay:
  service:
    base-url: ${PAY_SERVICE_BASE_URL}
    timeout: ${PAY_SERVICE_TIMEOUT:2000}
