apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
    - port: {{ .Values.monitoring.port }}
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}