name: pay-service

image:
  repository: pay-service
  tag: latest

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://my-postgresql:5432/paydb
  - name: SPRING_DATASOURCE_USERNAME
    value: payuser
  - name: SPRING_DATASOURCE_PASSWORD
    value: hyeonjin
