name: default-service

replicaCount: 1

image:
  repository: myrepo/default
  tag: latest

service:
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  cpu: 50

env:
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus


database:
  secretName: my-postgresql
